package bg.government.virusafe.app.utils

//General
const val COMMON_KEY = "Common."
const val ERROR_OCCURRED_LABEL = "Common.error_occurred_label"
const val GENERIC_ERROR_MSG = "Common.generic_error_msg"
const val NO_INTERNET_MSG = "Common.no_internet_msg"
const val SMTH_WENT_WRONG = "Common.something_went_wrong"
const val LOCATION_PERMISSION_MSG = "Common.location_permissions_msg"
const val TERMS_N_CONDITIONS_LBL = "Common.terms_n_conditions_label"
const val TOO_MANY_REQUESTS_MSG = "Common.too_many_requests_msg"
const val REDIRECT_TO_REGISTRATION_MSG = "Common.redirect_to_registration_msg"
const val HOUR_LABEL = "Common.hour_label"
const val HOURS_LABEL = "Common.hours_label"
const val MINUTE_LABEL = "Common.minute_label"
const val MINUTES_LABEL = "Common.minutes_label"
const val CONFIRM_LABEL = "Common.confirm_label"
const val FIELD_EMPTY_MSG = "Common.field_empty_msg"
const val FIELD_LENGTH_ERROR_MSG = "Common.field_length_error_msg"
const val FIELD_INVALID_FORMAT_MSG = "Common.field_invalid_format_msg"
const val YES_LABEL = "Common.yes_label"
const val NO_LABEL = "Common.no_label"
const val SAVE_CHANGES_LABEL = "Common.save_changes_label"
const val OK_LABEL = "Common.ok_label"
const val NEW_VERSION_LABEL = "Common.new_version_label"
const val NEW_VERSION_MSG = "Common.new_version_msg"
const val UPDATE_LABEL = "Common.update_label"
const val CONTINUE_LABEL = "Common.continue_label"
const val I_AGREE_LABEL = "Common.i_agree_label"
const val AND_LABEL = "Common.and_label"
const val SELECT_LANGUAGE = "Common.select_language"
const val I_AGREE_WITH_LBL = "Common.i_agree_with_label"
const val TERMS_N_CONDITIONS_SMALL_LBL = "Common.terms_n_conditions_small_caps_label"
const val I_CONSENT_TO_LBL = "Common.i_consent_to_label"
const val DATA_PROTECTION_NOTICE_SMALL_LBL = "Common.data_protection_notice_small_caps_label"
const val URL_ABOUT_COVID = "Common.url_about_covid"
const val URL_VIRUSAFE_WHY = "Common.url_virusafe_why"
const val TNC_TITLE = "Common.tnc_title"
const val TNC_PART_ONE = "Common.tnc_part_one"
const val TNC_PART_TWO = "Common.tnc_part_two"
const val DPN_TITLE = "Common.dpn_title"
const val DPN_DESCRIPTION = "Common.dpn_description"
const val DATA_PROTECTION_NOTICE_LBL = "Common.data_protection_notice_label"

//Registration
const val REGISTRATION_TITLE = "Common.registration_title"
const val MOBILE_HINT = "Common.mobile_hint"
const val VERIFICATION_CODE_TITLE = "Common.verification_code_title"
const val VERIFICATION_INFO_TEXT = "Common.verification_info_text"
const val VERIFICATION_CODE_HINT = "Common.verification_code_hint"
const val MISSING_VERIFICATION_CODE = "Common.missing_verification_code"
const val VERIFICATION_CODE_SEND_AGAIN = "Common.verification_code_send_again"
const val INVALID_PHONE_MSG = "Common.invalid_phone_msg"
const val INVALID_PIN_MSG = "Common.invalid_pin_msg"

//PersonalData
const val PERSONAL_DATA_TITLE = "Common.personal_data_title"
const val ID_NUMBER_HINT = "Common.identification_number_hint"
const val AGE_HINT = "Common.age_hint"
const val GENDER_MALE = "Common.gender_male"
const val GENDER_FEMALE = "Common.gender_female"
const val GENDER_HINT = "Common.gender_hint"
const val INVALID_AGE_MSG = "Common.invalid_age_msg"
const val INVALID_PRE_EXISTING_CONDITIONS_MSG = "Common.invalid_pre_existing_conditions_msg"
const val CHRONICAL_CONDITIONS_HINT = "Common.chronical_conditions_hint"
const val INVALID_MIN_AGE_MSG = "Common.invalid_min_age_msg"
const val FOREIGNER_NUMBER = "Common.identification_number_pin_segment"
const val PASSPORT_HINT = "Common.passport_hint"
const val USE_PERSONAL_DATA_TEXT_DISABLED = "Common.data_protection_deny_usage_label"

//Home
const val MY_CONTRIBUTION_TITLE = "Common.my_contribution_title"
const val MY_CONTRIBUTION_DESC = "Common.my_contribution_title_description"
const val HOW_IT_WORKS = "Common.how_it_works"
const val HOW_DO_YOU_FEEL = "Common.how_do_you_feel_today"
const val STATISTICS = "Common.statistics_label"
const val MY_PERSONAL_DATA = "Common.my_personal_data"
const val LEARN_MORE = "Common.learn_more"
const val LANGUAGE = "Common.language"

//SelfCheck
const val SELF_CHECK_TITLE = "Common.self_check_title"
const val NO_SYMPTOMS = "Common.no_symptoms"
const val WARNING_LABEL = "Common.warning_label"
const val WARNING_MSG = "Common.warning_msg"
const val DONE_TITLE = "Common.done_title"
const val DONE_MSG = "Common.done_msg"
const val TO_THE_HOME_LABEL = "Common.to_the_home_screen_label"
const val SELF_CHECK_TOO_MANY_REQUESTS_MSG = "Common.self_check_too_many_requests_msg"
